### PR TITLE
Tags

### PR DESCRIPTION
**Pull request by danohuiginn**

### CODE REVIEW

**Comment by danohuiginn** [comment]
@tanius, I've changed how we apply autocomplete, to avoid your race completion.

Note that you'll need to rebuild annotatorjs to test this.

**Comment by danohuiginn** [comment]
@tanius -- we also need to define what characters are allowed in tags. In particular, the tagging interface treats spaces as tag delimiters. If we're only allowing one tag at a time, we don't need that.

**Comment by tanius** [comment]
@danohuiginn Right, that. Thought about it, and my conclusion is that in addition to "normal" alphanumerical characters (full Unicode range), spaces and punctuation should also be allowed. Then it maps nicely to what is allowed in Drupal taxonomy terms and CATMA (I just checked). No need to add artificial restrictions, I think.

I also rethought the "one tag per annotation" thing. It still makes sense, I think. It makes our tagging plugin for annotator quite special-purpose, but so be it.

We can extend it in a later version to allow multiple tags per annotation without breaking the database structure (no extra table, using the "delta" column mechanism of Drupal instead). But then we also have to solve problems with access right (people will only have access to part of an annotation if the other tags are private). One tag per annotation is the usual case, and simplifies things.

**Comment by tanius** [comment]
@danohuiginn Tested your changes. Race condition is gone, and the auto-complete list updating (and creation of new tags) works find. Will merge this now, as the basic functionality works fine now and we can treat everything else as adding to this.

I think I start to get an impression of the "feel" of the ready product ... and I like it, this fast client-side auto-complete and stuff :+1:

**Pull request merged**
